language:
  ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem update bundler
  - npm install -g npm@3.x-latest
  - gem install rubocop
  - rubocop
  
