language:
  ruby

rvm:
  - 2.4.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem update bundler
  - gem install rspec-core
  - gem install rspec
  - gem install rubocop
  - rubocop

