language:
  ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem update bundler
  - bundle install
  - bundle exec rake compile
  - bundle exec rake teste container-based infrastructure for a faster build