language:
  ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem update bundler
  - rvm use system
  - sudo gem install cocoapods -v '0.39.0'
  - gem install rubocop
  - rubocop
  
